import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  return (
    <div className='flex flex-col bg-gradient-to-b from-slate-200 via-green-200 to-slate-200'>
      <Head>
        <title>Whatsapp Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='mx-auto p-6 text-3xl  animate-pulse'>
        Messages recieved
      </h1>
      <div className='px-5 py-3 drop-shadow-2xl rounded flex flex-col items-around mx-auto w-5/6  gap-4  '>
        <div className='flex  justify-between text-2xl'>
          <h2>Phone number</h2>
          <h2>message content</h2>
          <h2>replied?</h2>
        </div>
        <div className='flex flex-col items-between'>

        {
          data.map(message => {
            const { phone, content, isSent } = message
            return <div className='flex justify-between py-2 text-xl' key={message.id}>
              <div>{phone}</div>
              <div>{content}</div>
              <div>{isSent? 'yes' : 'no'}</div>
            </div>
          })
        }
        </div>

      </div>

    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3000/api/messages')
  const data = await res.json()
  return {
    props: {
      data: data
    }
  }
}
